### ISSUE TITLE
Typography and google fonts

### ISSUE THREAD

**Issue by Ryu-k** [reduxframework/redux-framework#3544] opened 2018-07-04 18:22 UTC
http://support.redux.io/?id=6sIuRgvgyRRxVR6lqnrXhiEh4juBMRmFIe%2BBGcKdHWoZoAl2jDv2QV2N4L3OOZOVv3rZ9IHxPjYTkKuW5KLkcQ%3D%3D

WordPress 4.9.6 
Redux  v3.6.9

Metaboxes extension installed.

I have an odd issue with the typography field, when I try to open the font dropdown I got this error.

select2.min.js?ver=3.5.2:formatted:1433 Uncaught TypeError: Cannot read property 'disabled' of undefined
    at h (select2.min.js?ver=3.5.2:formatted:1433)
    at d.populateResults (select2.min.js?ver=3.5.2:formatted:1461)
    at d.<anonymous> (select2.min.js?ver=3.5.2:formatted:1914)
    at Object.callback (select2.min.js?ver=3.5.2:formatted:1284)
    at select2.min.js?ver=3.5.2:formatted:276
    at Object.query (field_typography.min.js?ver=1530726963:1)
    at d.updateResults (select2.min.js?ver=3.5.2:formatted:1890)
    at d.opening (select2.min.js?ver=3.5.2:formatted:2023)
    at d.open (select2.min.js?ver=3.5.2:formatted:1683)
    at d.<anonymous> (select2.min.js?ver=3.5.2:formatted:2135)

If I re-upload the framework folder it re-start to work, I don't know why this is happening.

I am just wondering if you have any ideas.

Kind Regards

**Comment by kprovance** [comment] 2018-07-04 19:49
I can't reproduce based on your config.  I would begin disabling other plugins one at a time and see if there is a conflict there.  Specifically if another is using select 2.  I am assuming the option panel, if this is happening in metaboxes, that's a whole different story.

**Comment by kprovance** [comment] 2018-07-07 07:51
No reply given.  Closing.

**Closed by kprovance** 2018-07-07 07:51 UTC
