### ISSUE TITLE
image_select field with presets set to true is not working in latest version 

### ISSUE THREAD

**Issue by paulprodev** [reduxframework/redux-framework#2914] opened 2016-04-06 06:31 UTC
Redux Framework v3.5.9.8
WP Version 4.4.2

Hi to all,

We are developing a theme and we are using Redux for the theme options.
We are having a problem with image_select field type presets.

In our other option that uses image_select with no presets, it works fine. Once you choose and image and hit save, the chosen image retains the blue highlight border even when refreshed.

But for image_select with presets set to true, this is what happens:
1. I choose an image, a popup appears which says: Your current options will be replaced with the values of this preset.... etc.
2. I click on Ok. A blue border highlight appears around the image.
3. Page refreshes.
4. Once the page is loaded. The blue border around the chosen image is gone and a notice appears at the top of the redux options saying, "Settings Imported!"
4. When you go to the section of the options that is supposed to be changed by now, nothing changed. The preset values were not applied.

I tried resolving this with other options for several hours but the presets are definitely not working.

Looking forward to your response.

Thanks,

Paul

**Comment by kprovance** [comment] 2016-04-06 07:06
Unfortunately, I don;t have the time over the next week or so to delve into this.  Would you care?  If you find the cause, submit a pull request and we'll credit you.  :)

**Comment by kprovance** [comment] 2017-07-21 21:51
Fixed in v.3.6.5.3

**Closed by kprovance** 2017-07-21 21:51 UTC
