### ISSUE TITLE
How Can Update Redux Panel dynamically (by Codding)

### ISSUE THREAD

**Issue by ahmadmll** [reduxframework/redux-framework#3172] opened 2016-11-22 09:25 UTC
Hi My Dear Programmers...
I have installed a Wordpress theme that have used **Redux Panel 3.6** in it.
I Want to apply some setting on Redux Panel by codding and right code in functions.php file.
I found some helping on internet by all of theme are old and outdate,like this:  https://github.com/reduxframework/redux-framework/issues/772

thank you...

**Comment by kprovance** [comment] 2016-11-22 14:43
Well, the answers given in that post should have been sufficent.  You will need a solid understanding of PHP, plus we have an entire docs site that shows to to setup Redux, and use each field: https://docs.reduxframework.com.  If you're looking for us to write your code for you, that is a premium service, otherwise, you need to show us exactly what you've tried so far, plsu ALL the informationasked for in the new ticket window, which was as follows:  

Hello, and welcome to Redux Framework!

Are you a user reporting a bug with a theme or plugin?
======================================================
Redux is a tool for developers to include an options panel in their project. Consequently, we do not offer support for folks who have purchased a theme or plugin that uses Redux. The responsibility of support for themes and plugins falls upon it's author. We realize that some authors have included support links for Redux in their projects, when they should not have. We do apologize for that confusion and are taking steps to remedy this confusion. 

If you have purchased a theme or plugin that utilizes Redux, please contact the author for support. If the author is unavailable for support or has discontinued support, please refer to this before posting to our issue tracker: https://docs.reduxframework.com/core/support-defined/
	
Have a development usage question?
==================================
The issue tracker isn't the best place for usage questions. This format is not well-suited for Q&A, and questions here don't have as much visibility as they do elsewhere. Before you ask a question, here are some resources to get help first:

- Try Redux: https://demo.reduxframework.com/
- Read the docs: https://docs.reduxframework.com/
- Look for/ask questions on StackOverflow: https://stackoverflow.com/questions/tagged/redux-framework
- Ask in our community Slack channel: http://slack.redux.io/
- For Premium support or advanced customizations we offer premium support. See https://reduxframework.com/extension/premium-support/ for more information.

Questions about a Redux extension?
==================================
All pre-sale and support for premium extensions need to be posted to the Redux Extensions Issue Tracker. Please do not post them to this issue tracker. https://github.com/reduxframework/redux-extensions/

Think you found a bug?
======================
Please use the "BUG REPORT" template below. Remember, we are rabbid about backwards compatability. Do not submit fixes that break previous ways of doing so or they will be rejected.

Also, unless you provide a Support Hash, your request will also be rejected. See https://docs.reduxframework.com/core/generating-a-support-hash/ for more details.

You MUST be using Redux in dev mode when submitting an issue to us. If you are not, or have circumvented our dev mode protocol, you are on your own. There could be information in your issue that requires dev move active. (Compressed Javascript, for example. We are unable to diagnose issues with compressed Javascript and why dev mode needs to be enabled.)

If an error or notice appears on your screen, please cut and paste it into your issue. PLEASE, do not say you 'got an error' without telling us what the error or notice is.

Before you post, check the JavaScript!
======================================
Sometimes, an issue may be tied to JavaScript. To make this determination, you will need to check the JavaScript console. To do this, ensure your web browser is the topmost window. On your keyboard, press CTRL+SHIFT+I. The JavaScript console will open. If there are notices or errors there, please cut and paste them into your issue. We would prefer a cut and paste, since it will include all pertinent information. Also, Redux dev mode must be enabled so an accurate line number may be reported.


-->


## Support Hash

## Steps to reproduce

## Expected Behavior

## Actual Behavior

## Any Error Details (PHP/JavaScript)

**Comment by kprovance** [comment] 2016-11-25 14:16
No reply with requested information.  Closing.

**Closed by kprovance** 2016-11-25 14:16 UTC
