### ISSUE TITLE
1 byte file while generating custom theme

### ISSUE THREAD

**Issue by Michi23** [reduxframework/redux-framework#2421] opened 2015-06-23 05:46 UTC
...while using:
- several modern browsers
- two different computers

...and not using any type of:
- firewall
- antivirus software
- browser addon
- download manager

And yes, it happened in past. I bet there's global/local(per account) caching issue with the Builder. Those tips from similar reported issues are totally useless (I guess anyone doublechecked that before posting).

**Comment by AlexAlexandru** [comment] 2015-06-23 12:56
I genereted yesterday a theme and worked.I haven't generate one for like 2-3 months.

**Comment by Michi23** [comment] 2015-06-23 14:32
It might be user account-related, any ideas?

**Comment by AlexAlexandru** [comment] 2015-06-23 14:47
No maybe @dovy or @kprovance  they can help.Btw I just generated another to make sure its working and it is.

**Comment by kprovance** [comment] 2015-06-23 19:01
Can't reproduce.  We'll have to wait for @Dovy, especially if it's server related.

**Comment by kprovance** [comment] 2015-06-29 19:26
@Michi23 - Send your user account name and pw to info@reduxframework.com so I can see if it's a user account related thing.

**Comment by kprovance** [comment] 2015-07-02 18:58
Never received a reply or the requested information.  Closing.

**Closed by kprovance** 2015-07-02 18:58 UTC
