### ISSUE TITLE
Tiled Gallery Issue

### ISSUE THREAD

**Issue by maharrg** [reduxframework/redux-framework#2834] opened 2016-01-29 21:31 UTC
I've been having issues getting the "Tiled Mosaic" gallery feature to work in tandem with Redux. My blog, which is using Jetpack, can't seem to post any gallery type while Redux is active. When I turn off the plugin (which is required for my theme) the galleries post properly.

**Comment by kprovance** [comment] 2016-01-29 22:46
First, this: https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

Second, since there is no way for me to reproduce this, we'll need you to do a little more digging.  Please check for CSS conflicts.

**Comment by kprovance** [comment] 2016-01-31 18:33
No reply given.  Closing.

**Closed by kprovance** 2016-01-31 18:33 UTC
