### ISSUE TITLE
Error. There was a problem with your action. Please try again or reload the page.

### ISSUE THREAD

**Issue by OlgaBarlow** [reduxframework/redux-framework#3158] opened 2016-10-27 09:04 UTC
Hello,

First of all, thank you for such a great plugin you created!
We use your plugin to build Theme Options for our theme. Seems everything works fine, but one of our users faced the following problem http://prntscr.com/czivhx and we can see the following errors in console http://prntscr.com/czj0n5

Can't understand what can be the reason because we don't have such problem on our test installs and also no one of our users did not send similar issue. User has PHP7. Is there any compatibility issues with this version of PHP?

Could you point us in right direction to solve the problem? Would be very grateful.
Let me know if you need any other information.

Regards

**Comment by kprovance** [comment] 2016-10-27 12:06
Since this is happening specific on one of your client's servers, you're going to have to do some legwork to find the cause (if you want us to do is, it's a premium service at $100.00 an hour).  The third argument for _validate_values() is the $sections array.  I see you have modified our template for a different look?  (The support URL we requested for have been very helpful, and needed, you can use the same instructions provided to get that from your client).  If I had to guess, there some part of your options array that is not being properly passed to to template modification, or some option that is not properly filled out.  Was any of the core Redux code modified?

**Comment by OlgaBarlow** [comment] 2016-10-28 12:48
Hello,

Thank you for your reply. No, we did not change any core files, our users installing your plugin from official site, we did not include it in our theme. We changed CSS styles only. Once we comment out this code https://gyazo.com/972de98c0d27a722f85386997bd9438a in /plugins/redux-framework/ReduxCore/framework.php file on client's server error disappears. But we can't do this because after plugin update user will face this issue again. Is this issue from your side and you'll be able to fix missing argument or can be the other reason?

Regards

**Comment by OlgaBarlow** [comment] 2016-10-28 13:13
P.S. Today we got one more user with the same issue.

Regards

**Comment by dovy** [comment] 2016-10-28 14:39
Well, get us a support URL from one of those sites so we can debug.  ;)

**Comment by kprovance** [comment] 2016-10-28 16:43
As I said in Slack, that line deals specifically with extensions. Are you using extensions?  If so, which ones?  And I asked for it once, and it crucial now since this could also be an options array issue, we need to see a support URL from one of the affected users.  https://docs.reduxframework.com/core/generating-a-support-hash

**Comment by kprovance** [comment] 2016-10-28 23:05
Fixed in v.3.6.2.1

**Closed by kprovance** 2016-10-28 23:05 UTC

**Comment by OlgaBarlow** [comment] 2016-10-31 06:53
Thank you! 

Regards

**Comment by tannerhuynh** [comment] 2017-06-30 17:42
@OlgaBarlow and @kprovance 

I am having the same issue. Just bought my theme and installed it today with all the required plugins. I have not edited anything at all and this is a fresh install. Please tell me how this was fixed?

**Comment by kprovance** [comment] 2017-06-30 19:11
The reason the save is not working is because of that error 500 output.  It's up to the theme developer to go into your server to determine the cause. If he believes its a Redux issue, he is the one who gathers all the data he collected and then comes to us with that information.  If we supported every theme that uses Redux, we'd never get any work done, and why we have the system we do.
