### ISSUE TITLE
IE 10-11 Issue on Windows 7

### ISSUE THREAD

**Issue by ninzio** [reduxframework/redux-framework#3244] opened 2017-02-23 07:22 UTC
Hello, ReduxFramework team! First, let us say thank you for your work! It help us a lot! We use reduxframework in our themes on themeforest. We noticed an issue, that comes from the framework.php file. When you open the site in IE10-11 on Windows 7 it stops working. See example http://ninzio.com/lifefitness.

Can you take a look?

**Comment by dovy** [comment] 2017-02-23 16:11
I am unsure how we could be affecting this. We only provide code for fonts and dynamic CSS that gets added to the front-end. Could you provide additional details/screenshots? Not all of us have a Windows machine and it seems like this is less on our end, but we're willing to help if it makes sense.

**Comment by ninzio** [comment] 2017-02-24 06:54
Sure, please take a look at these two screenshots. First is our theme, the second one is the random theme from themeforest (not our theme), that uses reduxframework.

![untitled-1](https://cloud.githubusercontent.com/assets/25751154/23293424/785f845a-fa7f-11e6-81a6-27facc7bc1e1.jpg)
![untitled-2](https://cloud.githubusercontent.com/assets/25751154/23293425/786159e2-fa7f-11e6-9e70-c7eed5e98b89.jpg)

When we remove framework.php include, the issue is no longer present

**Comment by denniskuligin** [comment] 2017-03-04 15:06
Win8 11 IE / Win10 Edge - everything is fine...

Couldn't reproduce this bug.

**Comment by kprovance** [comment] 2017-03-05 05:13
I loaded up Win7 in a virtual machine and could not replicate.  You might want to check your windows logs, specifically the ones for Internet Explorer and see what's going on there.

**Comment by kprovance** [comment] 2017-03-08 20:53
Closing due to lack of reply.

**Closed by kprovance** 2017-03-08 20:53 UTC
