### ISSUE TITLE
Fix for ajax save and max_input_vars limit

### ISSUE THREAD

**Issue by harunbasic** [reduxframework/redux-framework#2631] opened 2015-09-25 17:32 UTC
Even if you are using serialized string when there are more options than max_input_vars allows there will be an error.

In the method ajax_save in the framework.php you are using parse_str() which depends on max_input_vars.

The code below isn't mine. I have found it and tested it. It works good and removes that limit which parse_str() adds. With this change Redux won't be limited by that.

All you have to do is replace the <code>parse_str( $_POST['data'], $values );</code> with <code>$values = redux_parse_str( $_POST['data'] );</code>
<pre>
/**
 * Parses the string into variables without the max_input_vars limitation.
 *
 * @since   1.0
 * @access  public
 * @param 	string $string
 * @return  array $result
 */
function redux_parse_str( $string ) {

	if ( '' == $string ) {
		return false;
	}

    $result = array();
    $pairs = explode( '&', urldecode( $string ) );

    foreach ( $pairs as $key => $pair ) {

    	// use the original parse_str() on each element
    	parse_str( $pair, $params );

    	$k=key( $params );

		if( ! isset( $result[$k] ) ) {
			$result+=$params;
		} else {
			$result[$k] = redux_array_merge_recursive_distinct( $result[$k], $params[$k] );
		}
    }

    return $result;
}

/**
 * Merge arrays without converting values with duplicate keys to arrays as array_merge_recursive does.
 *
 * As seen here http://php.net/manual/en/function.array-merge-recursive.php#92195
 *
 * @since   1.0
 * @access  public
 * @param 	array $array1
 * @param 	array $array2
 * @return 	array $merged
 */
function redux_array_merge_recursive_distinct( array $array1, array $array2 ) {
	$merged = $array1;
	foreach ( $array2 as $key => $value ) {
		if ( is_array( $value ) && isset( $merged[$key] ) && is_array( $merged[$key] ) ) {
			$merged[$key] = redux_array_merge_recursive_distinct ( $merged[$key], $value );
		} else {
			$merged[$key] = $value;
		}
	}

	return $merged;
}
</pre>

**Comment by kprovance** [comment] 2015-09-25 17:36
Generally, anyone with a panel with 1000 or more options is doing it wrong anyway.  Does this alter the way data is stored in the database?

**Comment by harunbasic** [comment] 2015-09-25 18:02
It doesn't alter how data is stored. parse_str() converts the serialized string into an array of options. This function does exactly the same. It creates exactly the same array as the parse_str() does but without that limit.

**Comment by kprovance** [comment] 2015-09-25 19:01
Okay.  Let me play with this.  I have to be sure such a change works under a few different conditions and doesn't cause breakage with our extensions library.  :)

**Comment by kprovance** [comment] 2015-09-25 20:40
I spoke to Dovy about this.  He says "use section ids, because if you don't, it uses the title in place, and that's why hes having issues."  There you go.  :)

**Comment by harunbasic** [comment] 2015-09-25 21:15
I think you have answered the wrong issue :). This is an issue with section ids. https://github.com/reduxframework/redux-framework/issues/2629 

This is about ajax save.

**Comment by kprovance** [comment] 2015-09-25 21:16
Yeah, whoops.  My bad.  Still paying with your code.  So far, so good.  Has to pass the customizer test yet.  ;-)

**Comment by harunbasic** [comment] 2015-09-26 01:43
Just found out that in the text fields it removes the + sign. Needs a bit tuning. I'm working on a solution.

**Comment by kprovance** [comment] 2015-09-26 01:51
Another field or two you might want to also check (which I have not yet, as I'm working on something else), would be the ACE Editor and WP Editor.  We've had issues with those fields in the past in terms of ajax save.

**Comment by kprovance** [comment] 2015-09-26 03:19
I can confirm that the + sign also disappears in the ACE Editor.

**Comment by harunbasic** [comment] 2015-09-26 03:20
Fixed it. In the redux_parse_str() the urldecode() isn't necessary and was the reason why the + was disappearing.

Insted <code>$pairs = explode( '&', urldecode( $string ) );</code> there should be only <code>$pairs = explode( '&', $string );</code>.

I have tested it with all characters on my keyboard and it works like it should.

**Comment by kprovance** [comment] 2015-09-26 03:30
Confirmed.  Cool.  Okay, still putting this through it's paces.  So far so good.  :)

**Comment by anikitas** [comment] 2015-10-02 13:25
Hello,

I have the same issue too with 1015 variables. I know that i have a large config file.

I usually have max_inputs_vars more than the default 1000, i switched back to the default value 1000 to see how Redux reacts.

Tested also the code and looks that it can save now properly with ajax.

Will you include similar implementation to this in one of the next releases?

Thanks in advance!

**Comment by anikitas** [comment] 2015-10-02 14:33
I will test it again,

I think multi select is not saving correctly with this code.

I tested a field:
<pre>
'type'     => 'select',
'data'     => 'post_type',
'multi'    => true,
</pre>

It saves only one value not all selected.

**Comment by anikitas** [comment] 2015-10-02 15:59
I think the recursive function needs a little modification.

<pre>
function redux_array_merge_recursive_distinct( array $array1, array $array2 ) {
    $merged = $array1;
    foreach ( $array2 as $key => $value ) {
        if ( is_array( $value ) && isset( $merged[$key] ) && is_array( $merged[$key] ) ) {
            $merged[$key] = redux_array_merge_recursive_distinct ( $merged[$key], $value );
        } else if ( is_numeric( $key ) ) {
			if ( !in_array( $value, $merged ) ) {
                $merged[] = $value;
			}		
		} else {
            $merged[$key] = $value;
        }
    }

    return $merged;
}
</pre>

You can double check if you want!

**Comment by kprovance** [comment] 2015-10-03 18:33
@harunbasic , can you confirm?  I admit, I've not had time to do so yet.

**Comment by harunbasic** [comment] 2015-10-05 15:42
Yes, multi select and multi text wasn't working. It was saving only the last value.

@anikitas your code fixed multi select but broke multi checkbox with data and other fields that used unique integer for key.

Here is the recursive function that is working for all fields.
<pre>
function redux_array_merge_recursive_distinct( array $array1, array $array2 ) {
    $merged = $array1;
    foreach ( $array2 as $key => $value ) {
        if ( is_array( $value ) && isset( $merged[$key] ) && is_array( $merged[$key] ) ) {
            $merged[$key] = redux_array_merge_recursive_distinct( $merged[$key], $value );
        } else if ( is_numeric( $key ) && isset( $merged[$key] ) ) {
            $merged[] = $value;  
        } else {
            $merged[$key] = $value;
        }
    }

    return $merged;
}
</pre>

I have gone through all fields in the sample-config.php and checked it.

**Comment by anikitas** [comment] 2015-10-05 15:49
Great!
I will test it later on. Thanks.

**Comment by anikitas** [comment] 2015-10-12 20:44
I think the last function is the best. It fixes the multi fields, otherwise the result is not the same.
I made several tests, comparing the outputs with the sample-config.php, With the last method the outputs are identical.

I also found a notice in the process. Not related with the alternative method of saving the fields.

You can reproduce it in debug mode with the sample config file, if you Reset All or Reset Section
Found in the following menu: Basic Fields - Radio - Radio Option w/ Menu Data

Notice: Array to string conversion in C:\wamp\www\blade\wp-includes\general-template.php on line 3261

I made all tests again with: Redux v3.5.8

**Comment by anikitas** [comment] 2015-10-13 09:36
On the safe side a developer could add a setting in options to switch between two functions.
The developer can decide to use the second method if he has many parameters, so current installations are not affected.

Like the ajax_save parameter e.g: ajax_max_input

<pre>
if ( isset( $redux->args['ajax_max_input'] ) && $redux->args['ajax_max_input'] == true ) {
	$values = $this->redux_parse_str( $_POST['data'] );
} else {
	parse_str( $_POST['data'], $values );
}
</pre>

Just a thought!

**Comment by harunbasic** [comment] 2015-10-13 14:58
I also think this is a good idea to have that option.

Until this gets implemented you could just create your own save method and overwrite the default one.

The functios are renamed but do the same thing and you will need to replace the <code>apalodi_options</code> with your <code>opt_name</code>.

<pre>
if ( ! function_exists( 'apalodi_redux_ajax_save' ) ) {
	/**
	 * Custom redux ajax save that has not a limit for max_input_vars
	 * because we aren't using the parse_str functions. We are using custom apalodi_parse_str function.
	 *
	 * @since   1.0
	 * @access  public
	 * @return  array $return_array
	 */
	function apalodi_redux_ajax_save() {

		if ( ! wp_verify_nonce( $_REQUEST['nonce'], "redux_ajax_nonceapalodi_options" ) ) {
			echo json_encode( array(
				'status' => __( 'Invalid security credential.  Please reload the page and try again.', 'apalodi' ),
				'action' => ''
			) );
			
			die();
		}
		
		if ( ! current_user_can ( 'manage_options' ) ) {
			echo json_encode( array(
				'status' => __( 'Invalid user capability.  Please reload the page and try again.', 'apalodi' ),
				'action' => ''
			) );
			
			die();
		}
		
		$redux = ReduxFrameworkInstances::get_instance( 'apalodi_options' );
		$dir = $redux::$_dir;

		if ( ! empty( $_POST['data'] ) ) {

			$values = array();

			$_POST['data'] = stripslashes( $_POST['data'] );
			//parse_str( $_POST['data'], $values );
			$values = apalodi_parse_str( $_POST['data'] );
			$values = $values['apalodi_options'];

			if ( function_exists( 'get_magic_quotes_gpc' ) && get_magic_quotes_gpc() ) {
				$values = array_map( 'stripslashes_deep', $values );
			}

			if ( ! empty ( $values ) ) {

				try {
					if ( isset( $redux->validation_ran ) ) {
						unset( $redux->validation_ran );
					}
					$redux->set_options( $redux->_validate_options( $values ) );

					$do_reload = false;
					if ( isset( $redux->reload_fields ) && ! empty( $redux->reload_fields ) ) {
						if ( ! empty( $redux->transients['changed_values'] ) ) {
							foreach ( $redux->reload_fields as $idx => $val ) {
								if ( array_key_exists( $val, $redux->transients['changed_values'] ) ) {
									$do_reload = true;
								}
							}
						}
					}
					
					if ( $do_reload || ( isset ( $values['defaults'] ) && ! empty ( $values['defaults'] ) ) || ( isset ( $values['defaults-section'] ) && ! empty ( $values['defaults-section'] ) )) {
						echo json_encode( array( 'status' => 'success', 'action' => 'reload' ) );
						die ();
					}

					require_once $dir . 'core/enqueue.php';
					$enqueue = new reduxCoreEnqueue( $redux );
					$enqueue->get_warnings_and_errors_array();

					$return_array = array(
						'status'   => 'success',
						'options'  => $redux->options,
						'errors'   => isset ( $redux->localize_data['errors'] ) ? $redux->localize_data['errors'] : null,
						'warnings' => isset ( $redux->localize_data['warnings'] ) ? $redux->localize_data['warnings'] : null,
					);

				} catch ( Exception $e ) {
					$return_array = array( 'status' => $e->getMessage() );
				}
			} else {
				echo json_encode( array( 'status' => __( 'Your panel has no fields. Nothing to save.', 'apalodi' ) ) );
			}
		}

		if ( isset( $return_array ) ) {
			if ( $return_array['status'] == "success" ) {
				require_once $dir . 'core/panel.php';
				$panel = new reduxCorePanel( $redux );
				ob_start();
				$panel->notification_bar();
				$notification_bar = ob_get_contents();
				ob_end_clean();
				$return_array['notification_bar'] = $notification_bar;
			}

			echo json_encode( apply_filters( "redux/options/apalodi_options/ajax_save/response", $return_array ) );
		}

		die ();

	}
}
remove_action( 'wp_ajax_apalodi_options_ajax_save', array( 'ReduxFramework', 'ajax_save' ) );
add_action( 'wp_ajax_apalodi_options_ajax_save', 'apalodi_redux_ajax_save' );
</pre>

**Comment by anikitas** [comment] 2015-10-13 16:10
I can wait a week, part of the code is already present in the latest version of Redux.

Function redux_array_merge_recursive_distinct needs to be updated and possibly the check in the ajax_save function.

Of course this is up to Kevin how to implement it.

**Comment by kprovance** [comment] 2015-10-13 16:32
Okay, status check.  :)

I'm not sure where we are on the most final form of this code.  The functions are currently in the core, but their not being run yet, as I thought a problem with button_set prevented it?  Am I remembering that correctly?

As it stands now, what the are current (and working) versions of these functions, so I can update the core.

I could add the argument to turn it off, but I have to ask why?  What would be a reason to want to turn it on or off?

**Comment by anikitas** [comment] 2015-10-13 16:42
Function redux_array_merge_recursive_distinct needs to be updated with this one. It has one more check.

<pre>
function redux_array_merge_recursive_distinct( array $array1, array $array2 ) {
    $merged = $array1;
    foreach ( $array2 as $key => $value ) {
        if ( is_array( $value ) && isset( $merged[$key] ) && is_array( $merged[$key] ) ) {
            $merged[$key] = redux_array_merge_recursive_distinct( $merged[$key], $value );
        } else if ( is_numeric( $key ) && isset( $merged[$key] ) ) {
            $merged[] = $value;  
        } else {
            $merged[$key] = $value;
        }
    }

    return $merged;
}
</pre>

The switch could be as a precaution for further testing. Or if we find a issue to be able to switch it back to the old method that works well for < 1000 parameters.

Some fields require more parameters than others ( like Typography ) thus you end up with many params.

As you said not everybody uses more than 1000 parameters in total.

**Comment by harunbasic** [comment] 2015-10-13 17:24
I was thinkg if you aren't done with testing and aren't quite sure should you use this save method that you could add that switch so only developers that want this new save method can use it.

But if you are done with all testing and you think that there is no reason to use the old parse_str anymore then the switch isn't necessary.

As I said before I have gone through all fields in the sample-config.php and everything is working like it should.

**Comment by kprovance** [comment] 2016-01-22 23:10
@harunbasic -I know it's been a while since I visited this.  I was going to patch this back in and give it another run.  Maybe WordPress did something since this code, I don't know...but as it stands, something either isn;t saving or being retrieved properly.  For example, if one sets an switch option to a new setting, and clicks Save, everything looks kosher.  Hit refresh, and the setting reverts.  Somewhere between Oct and now, something got wonky.

Are you still using this code?  Does it need to be updated?

Thanks!

**Comment by kprovance** [comment] 2016-01-22 23:35
I did a little leg work for this:

As it stands, the saves made with this code ARE saving to the database.  However, when refreshing the page, the values are not being pulled from the database...everything is the default value.  I can only surmise there is something in the save cause Redux to not see the proper values and load the default?  Not sure.  Don;t have the time to dig into the why of it all, but that seems to be the standing issue.

Cheers.

**Comment by kprovance** [comment] 2016-01-22 23:44
Okay, you know what?  Never mind any of what I just wrote.  I'm a freakin' idiot sometimes.  The fault was completely mine, commenting out the wrong bloody line!  Ugh!  :)

So far so good.  I'm thinking we'll push this to our repo  and see what happens with a broader audience.

Cheers.

**Comment by kprovance** [comment] 2016-01-22 23:56
Adding manually.  If new issues crop up, let's start a new thread for it.

**Closed by kprovance** 2016-01-22 23:56 UTC

**Comment by designsvilla** [comment] 2016-03-17 21:44
new version not saving options with ajax_save set to true

**Comment by kprovance** [comment] 2016-03-17 22:00
Sorry, but it does.  Tens of thousands of people use it daily.  However, you're going to need to be WAY more specific.  Please review: https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by designsvilla** [comment] 2016-03-18 11:29
i am using redux in my project earlier version was working fine. i have just integrate new version and every thing working fine except options not saving when ajax_save is true and console shows error 

There was an error saving. Here is the result of your action
<br />
<b>Catchable fatal error</b>:  Argument 1 passed to ReduxFramework::redux_array_merge_recursive_distinct() must be of the type array, string given, called in D:\xamp\htdocs\wordpress\helpme\helpme\wp-content\themes\helpme\includes\framework\ReduxCore\framework.php on line 3914 and defined in <b>D:\xamp\htdocs\wordpress\helpme\helpme\wp-content\themes\helpme\includes\framework\ReduxCore\framework.php</b> on line <b>3935</b><br />


while if ajax_save is false its working fine 

i think max_input_vars delimiter need some work

**Comment by harunbasic** [comment] 2016-03-19 03:14
I'm using it and there are no problems. Are you using some custom field or is the error accuring on some default field? 

Attach your files (config file and maybe your custom field if there is one) so we can see.

**Comment by designsvilla** [comment] 2016-03-19 13:54
these are framework and config files

**Comment by harunbasic** [comment] 2016-03-19 17:15
Where are they? I don't see anything.

**Comment by designsvilla** [comment] 2016-03-19 18:16
in attachment

**Comment by kprovance** [comment] 2016-03-19 18:18
There are no attachments on the issue tracker, mate.  And this is not being done via email.  Use Gist to provide the information:  https://gist.github.com/

Thanks for stepping back in @harunbasic.  :)

**Comment by designsvilla** [comment] 2016-03-19 18:20
sorry attachments was sent through mail please find here

[ReduxCore.zip](https://github.com/reduxframework/redux-framework/files/180948/ReduxCore.zip)

**Comment by kprovance** [comment] 2016-03-19 18:22
Okay, you're not understanding what we need here.  We don't need a zip of our own code base.  I already have that, since I'm one of the devs, right?

What we need is your options config.  We have to be able to reproduce your particular issue.  We cannot fix what we cannot break.

Thanks.  :)

**Comment by designsvilla** [comment] 2016-03-19 18:23
option-config is attached in zip which is i am using for
