### ISSUE TITLE
Redux theme options values updated to default one when WordPress version is updated, why?

### ISSUE THREAD

**Issue by ArchanaSharma95** [reduxframework/redux-framework#3916] opened 2022-10-29 04:40 UTC
These are the list of arguments I have defined::

```
$args = array(
	// TYPICAL -> Change these values as you need/desire
	'opt_name' => $opt_name,
	// This is where your data is stored in the database and also becomes your global variable name.
	'display_name' => $theme->get('Name'),
	// Name that appears at the top of your panel
	'display_version' => $theme->get('Version'),
	// Version that appears at the top of your panel
	'menu_type' => 'menu',
	//Specify if the admin menu should appear or not. Options: menu or submenu (Under appearance only)
	'allow_sub_menu' => true,
	// Show the sections below the admin menu item or not
	'menu_title' => esc_html__('Theme Options', 'myThemeName'),
	'page_title' => esc_html__('Theme Options', 'myThemeName'),
	// You will need to generate a Google API key to use this feature.
	// Please visit: https://developers.google.com/fonts/docs/developer_api#Auth
	'google_api_key' => '',
	// Set it you want google fonts to update weekly. A google_api_key value is required.
	'google_update_weekly' => false,
	// Must be defined to add google fonts to the typography module
	'async_typography' => true,
	// Use a asynchronous font on the front end or font string
	//'disable_google_fonts_link' => true,                    // Disable this in case you want to create your own google fonts loader
	'admin_bar' => true,
	// Show the panel pages on the admin bar
	'admin_bar_icon' => 'dashicons-portfolio',
	// Choose an icon for the admin bar menu
	'admin_bar_priority' => 50,
	// Choose an priority for the admin bar menu
	'global_variable' => '',
	// Set a different name for your global variable other than the opt_name
	'dev_mode' => false,
	// Show the time the page took to load, etc
	'forced_dev_mode_off' => false,
	'disable_tracking' => true,
	'update_notice' => true,
	// If dev_mode is enabled, will notify developer of updated versions available in the GitHub Repo
	'customizer' => true,
	// Enable basic customizer support
	//'open_expanded'     => true,                    // Allow you to start the panel in an expanded way initially.
	//'disable_save_warn' => true,                    // Disable the save warning when a user changes a field
	// OPTIONAL -> Give you extra features
	'page_priority' => null,
	// Order where the menu appears in the admin area. If there is any conflict, something will not show. Warning.
	'page_parent' => 'themes.php',
	// For a full list of options, visit: http://codex.wordpress.org/Function_Reference/add_submenu_page#Parameters
	'page_permissions' => 'manage_options',
	// Permissions needed to access the options panel.
	'menu_icon' => '',
	// Specify a custom URL to an icon
	'last_tab' => '',
	// Force your panel to always open to a specific tab (by id)
	'page_icon' => 'icon-themes',
	// Icon displayed in the admin panel next to your menu_title
	'page_slug' => '',
	// Page slug used to denote the panel, will be based off page title then menu title then opt_name if not provided
	'save_defaults' => true,
	// On load save the defaults to DB before user clicks save or not
	'default_show' => false,
	// If true, shows the default value next to each field that is not the default value.
	'default_mark' => '',
	// What to print by the field's title if the value shown is default. Suggested: *
	'show_import_export' => true,
	// Shows the Import/Export panel when not used as a field.

	// CAREFUL -> These options are for advanced use only
	'transient_time' => 60 * MINUTE_IN_SECONDS,
	'output' => true,
	// Global shut-off for dynamic CSS output by the framework. Will also disable google fonts output
	'output_tag' => true,
	// Allows dynamic CSS to be generated for customizer and google fonts, but stops the dynamic CSS from going to the head
	// 'footer_credit'     => '',                   // Disable the footer credit of Redux. Please leave if you can help it.

	// FUTURE -> Not in use yet, but reserved or partially implemented. Use at your own risk.
	'database' => '',
	// possible: options, theme_mods, theme_mods_expanded, transient. Not fully functional, warning!
	'use_cdn' => true,
	// If you prefer not to use the CDN for Select2, Ace Editor, and others, you may download the Redux Vendor Support plugin yourself and run locally or embed it in your code.

	// HINTS
	'hints' => array(
		'icon' => 'el el-question-sign',
		'icon_position' => 'right',
		'icon_color' => 'lightgray',
		'icon_size' => 'normal',
		'tip_style' => array(
			'color' => 'red',
			'shadow' => true,
			'rounded' => false,
			'style' => '',
		),
		'tip_position' => array(
			'my' => 'top left',
			'at' => 'bottom right',
		),
		'tip_effect' => array(
			'show' => array(
				'effect' => 'slide',
				'duration' => '500',
				'event' => 'mouseover',
			),
			'hide' => array(
				'effect' => 'slide',
				'duration' => '500',
				'event' => 'click mouseleave',
			),
		),
	),
);
$opt_name = "my_options";
Redux::setArgs($opt_name, $args);
Redux::setSection($opt_name, array(
	'title' => esc_html__('General Options', 'myThemeName'),
	'id' => 'general_options',
	'desc' => esc_html__('Theme general options!', 'myThemeName'),
	'customizer_width' => '400px',
	'icon' => 'el el-cogs',
	'fields' => array(
		array(
			'id' => 'site_layout',
			'type' => 'button_set',
			'title' => esc_html__('Site Layout', 'myThemeName'),
			'subtitle' => esc_html__('Set the layout of your site', 'myThemeName'),
			'options' => array(
				'full' => 'Full Width',
				'boxed' => 'Boxed',
			),
			'default' => 'full',
		),
		array(
			'id' => 'container_width',
			'type' => 'text',
			'title' => esc_html__('Container Width', 'myThemeName'),
			'subtitle' => esc_html__('Set the container width', 'myThemeName'),
			'default' => '1170px',
		),
		array(
			'id' => 'hide_page_loader',
			'type' => 'switch',
			'title' => esc_html__('Enable/Disable Page Loader', 'myThemeName'),
			'subtitle' => esc_html__('Set off to disable page loader.', 'myThemeName'),
			'default' => true,
		),
		array(
			'id' => 'page_spacing',
			'type' => 'spacing',
			'mode' => 'padding',
			'units' => array('em', 'px', '%'),
			'title' => esc_html__('Page Spacing', 'myThemeName'),
			'subtitle' => esc_html__('Set the page spacing from top and bottom', 'myThemeName'),
			'left' => false,
			'right' => false,
			'default' => array(
				'padding-top' => '70px',
				'padding-bottom' => '70px',
			),
		),
		array(
			'id' => 'code_before_head',
			'type' => 'textarea',
			'title' => esc_html__('Code Before Closing Head Tag', 'myThemeName'),
			'subtitle' => esc_html__('Enter code that you want to place before closing the head tag', 'myThemeName'),
			'default' => '',
		),
		array(
			'id' => 'code_before_body',
			'type' => 'textarea',
			'title' => esc_html__('Code before Closing Body Tag ', 'myThemeName'),
			'subtitle' => esc_html__('Enter code that you want to place before closing the body tag', 'myThemeName'),
			'default' => '',
		),
		array(
			'id' => 'btm_top_icon',
			'type' => 'switch',
			'title' => esc_html__('Enable/Disable Bottom To Top Icon', 'myThemeName'),
			'subtitle' => esc_html__('Option to enable/disable the bottom to top icon.', 'myThemeName'),
			'default' => true,
		),
		array(
			'id' => 'general_border_radius',
			'type' => 'button_set',
			'title' => esc_html__('Design Layout', 'myThemeName'),
			'subtitle' => esc_html__('Select the site border, icon layout etc', 'myThemeName'),
			'options' => array(
				'round' => 'Rounded',
				'square' => 'Square',
			),
			'default' => 'round',
		),
	),
)
);
```

Please tell me, if I need to make any changes

**Comment by kprovance** [comment] 2022-10-29 04:43
I've never heard of that happening.

**Comment by ArchanaSharma95** [comment] 2022-10-29 06:23
> I've never heard of that happening.

Please check the description I have mentioned. Every time the WordPress version updates my option value revert to the default one. Like I have added an option for the site logo, and other descriptions but my options revert to default empty values. Is there any argument I have added wrong or missed anything ?? Please help, any suggestion would be appreciated thanks!

**Comment by kprovance** [comment] 2022-10-29 22:43
I don't see anything wrong (I would use something other than `my_options` as it's generic and could easily be used by other people who didn't want to use an original opt_name. Disclaimer, changing the opt_name WILL reset your options. Do it now before it's too late in the development process.

Redux stores options in the wp_options database under the opt_name. That information doesn't get erased between WordPress updates...and if it does, that would be a WordPress issue, not a Redux issue.  If Redux were the cause, there would be literally millions of complaints, and I've never heard of this happening. Are you able to reproduce this across multiple sites on multiple servers?

**Comment by ArchanaSharma95** [comment] 2022-10-31 11:04
> opt_name

I'm having this issue on multiple sites. Not able to understand why this is happening.

**Comment by ArchanaSharma95** [comment] 2022-10-31 11:08
> opt_name

And instead of "my_options", I have used my theme name with an underscore and options "mytheme_options", where mytheme is my theme name. Still not able to find out an issue.

**Comment by kprovance** [comment] 2022-10-31 16:23
I'm not sure what to tell you. I've seen no evidence this is a Redux issue, but rather something else tampering with the database. I can't fix something I cannot reproduce, or is even broken.

**Comment by ArchanaSharma95** [comment] 2022-11-01 06:54
> I'm not sure what to tell you. I've seen no evidence this is a Redux issue, but rather something else tampering with the database. I can't fix something I cannot reproduce, or is even broken.

I found the problem. I have created a plugin that is basically a theme helper plugin. Whenever user will activate this plugin then he will get the redux options and other functionalities. And I have created theme redux options file inside the theme. Now, whenever I am deactivating the helper function my theme options hides and after activation its shows the default values instead of the last saved one.

**Comment by kprovance** [comment] 2022-11-01 07:11
1) Redux database is stored in the WordPress table under the wp_options row under the column option_name under the project's opt_name, whatever that may be. The data is stored as a serialized string.

2) By default, deactivating a plugin does NOT delete its data. Custom code has to be added to the plugin to achieve that end. 

As this is not a Redux issue, I am closing the ticket.  Good luck!

**Closed by kprovance** 2022-11-01 07:11 UTC
