### ISSUE TITLE
Set field function with priority option

### ISSUE THREAD

**Issue by ahmedp** [reduxframework/redux-framework#3073] opened 2016-08-02 12:07 UTC
I am developing child theme and i have added fields  in existing section of parent theme. I used set field function for creating field in existing panel. I have added priority option but it's printing some numbers on my admin panel screen. Please try set field function with priority. Priority is working fine but problem is why it's printing number on screen. Below is my code. 

Redux::setField(
    $opt_name, // This is your opt_name,	
		 array(
            'id'        => 'educationpress_header_variation',
            'type'      => 'image_select',
            'title'     => esc_html__( 'Header Variation', 'edupress-woo-child' ),
            'subtitle'  => esc_html__( 'Select the header that you want to use for site.', 'edupress-woo-child' ),
			'section_id' => 'header-section',
            'options'   => array(
                '1' => array(
                    'title' => esc_html__('1st Header', 'edupress-woo-child'),
                    'img' => get_stylesheet_directory_uri() . '/inc/theme-options/images/header1.jpg',
                ),
                '2' => array(
                    'title' => esc_html__('2nd Header', 'edupress-woo-child'),
                    'img' => get_stylesheet_directory_uri() . '/inc/theme-options/images/header2.jpg',
                ),
				'3' => array(
                    'title' => esc_html__('3rd Header', 'edupress-woo-child'),
                    'img' => get_stylesheet_directory_uri() . '/inc/theme-options/images/header3.jpg',
                ),
            ),
			'priority' => '3',
            'default'   => '1',
			
        )
	);

Thanks

**Comment by kprovance** [comment] 2016-08-02 15:17
I can't try the code because I don;t have your theme or your child theme.  Assistance with modifying someone else theme is going to fall under premium support, as it will require me going onto your server. Looking at this code, I don't see any statements that would cause output.  If you can provide a screenshot of this output, great, but this is not something I can reproduce easily.

**Comment by kprovance** [comment] 2016-08-04 02:01
Closing due to lack of reply.

**Closed by kprovance** 2016-08-04 02:01 UTC
