### ISSUE TITLE
ReduxFramework crashing my website

### ISSUE THREAD

**Issue by Tjsup** [reduxframework/redux-framework#2788] opened 2016-01-05 03:59 UTC
After updating to the newest version of wordpress I have been unable to active the ReduxFramework plugin as it crashes my whole website and i get a white page. I have had to active one plugin at a time and work out what is causing my website to crash, but I can guarantee it is the ReduxFramework plugin. 

I use the flaton pro theme and use redux to allow me to change the colour of the theme etc. 

Any idea why the plugin might be causing my website to completely crash (white page).

Thanks,

**Comment by dovy** [comment] 2016-01-05 04:01
Can you try installing Redux from this Repo as it it were a plugin. Then let us know if the issue is resolved. If so, it's time to push an update to WP.org.  ;)

**Comment by Tjsup** [comment] 2016-01-05 04:21
Forgive me as I am a bit thick, but what do you mean from this repo?

**Comment by dovy** [comment] 2016-01-05 04:30
Not at all. Download this, and expand it. Then install it as the plugin you need:
https://github.com/reduxframework/redux-framework/archive/master.zip

This should take the place of redux-frameowork.

So first, delete the ReduxFramework plugin. Then install the above URL as a plugin.  :)

**Comment by kprovance** [comment] 2016-01-05 07:51
<blockquote>
I use the flaton pro theme and use redux to allow me to change the colour of the theme etc. 
</blockquote>

Are you the actual theme developer?  It would be incredibly helpful to us - if you are - to review our posting guidelines and supply us with the necessary information:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment] 2016-01-06 19:48
No reply within two days.  Closing.

**Closed by kprovance** 2016-01-06 19:48 UTC

**Comment by Tjsup** [comment] 2016-01-11 06:39
Hi dovy. Sorry for the late reply the Manager of IT at my organisation only returned from leave today and I was waiting until he was back just incase the website crashes again. 

We did what you said and it still does not work. Ive tried deactiving every other plugin and only activating Redux and nope still makes the whole website crash.

I am using:
WordPress 4.4.1
FlatOn ProVersion: 1.4.0
Redux Version 3.5.8.15 

Any other suggestions/ideas?

**Comment by Tjsup** [comment] 2016-01-11 06:57
Further to the above.
 Here is the config of our server. Please bear in mind that this is an Intranet page so there is no public access.

•Apache/2.4.7 (Ubuntu)
•Database client version: libmysql – 5.5.44
•PHP extension: mysqli Documentation
•Server: Localhost via UNIX socket
•Server type: MySQL
•Server version: 5.5.44-0ubuntu0.14.04.1 – (Ubuntu)
•Protocol version: 10
•User: wpdbuser@localhost
• Server charset: UTF-8 Unicode (utf8) 

If you would like to see this for youreself, I am happy to run a Teamviewer session, I just need to know your timezone. We are +8GMT.

**Comment by venkatraj** [comment] 2016-01-11 08:15
Just to clarify
@dovy  and @kprovance 

I'm theme author and using Redux with most of my themes.
I could say that Theme and Redux work properly on our dev server, demo server and clients sites / server.

@Tjsup Please make sure to deactivate all plugins and activate 'TwentySixteen' theme, then activate 'Redux' to see if it crashes website? That way, we can be sure that it is not Theme issue. Thanks

**Comment by kprovance** [comment] 2016-01-11 09:40
For us to go into your server is a premium support option.  It's not free.  That said, you need to examine your PHP error logs to determine where the fatal error is occurring.  If Redux is mentioned, post it back here.  If it's something else, that's something you'll have to handle yourself.

**Comment by Tjsup** [comment] 2016-01-12 02:17
I upgraded the PHP Memory Limit from 128mb to 256mb and restarted apache2 service with no joy, therefore reverted it.

We disabled all plugins, changed to a different theme
enabled redux on the twenty thirteen theme and it failed

We checked the error.log for php and this is what it returns when enabling redux:
[Tue Jan 12 09:49:18.045827 2016] [mpm_prefork:notice] [pid 8176] AH00169: caught SIGTERM, shutting down
[Tue Jan 12 09:49:18.867965 2016] [mpm_prefork:notice] [pid 8254] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.11 configured -- resuming normal operations
[Tue Jan 12 09:49:18.868102 2016] [core:notice] [pid 8254] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jan 12 09:49:26.688229 2016] [:error] [pid 8261] [client 172.20.153.27:59863] PHP Fatal error:  Call to undefined function wp_generate_password() in /var/www/html/wp-admin/includes/file.php on line 169, referer: http://somnet/wp-admin/plugins.php
[Tue Jan 12 09:49:30.198149 2016] [:error] [pid 8260] [client 172.20.153.27:59879] PHP Fatal error:  Call to undefined function wp_generate_password() in /var/www/html/wp-admin/includes/file.php on line 169
[Tue Jan 12 09:49:30.560523 2016] [:error] [pid 8262] [client 172.20.153.27:59883] PHP Fatal error:  Call to undefined function wp_generate_password() in /var/www/html/wp-admin/includes/file.php on line 169
[Tue Jan 12 09:49:44.730013 2016] [:error] [pid 8267] [client 172.20.148.1:50461] PHP Fatal error:  Call to undefined function wp_generate_password() in /var/www/html/wp-admin/includes/file.php on line 169

**Comment by kprovance** [comment] 2016-01-12 02:22
I'm confused.  Standard theme included with Wordpress do not use Redux Framework.  Redux is for developers to add options to their own theme.  Downloading it and installing ti doesn;t give you the ability to change the options on any given theme.

Even so, the errors listed are not related to Redux.  Redux does not use the wp_generate_password() call anywhere.  I am still unable to see where Redux is the cause.

**Comment by Tjsup** [comment] 2016-01-12 02:27
You are right. It must be an internal error. 

Please close this. I will keep looking into what my issue is

**Comment by hhbrown123** [comment] 2016-03-04 02:19
I am receiving the "Fatal error: Call to undefined function menu_page_url() in /home/forthepeople/public_html/wp-content/themes/campaign/framework-customizations/extensions/shortcodes/shortcodes/section/options.php on line 6" after upgrading the extensions.

Can anyone help with resolution? My site is http://www.campaignforpeople.com/

Thanks

**Comment by dovy** [comment] 2016-03-04 19:32
@hhbrown123 Hello there. I fear that "redux-framework" is not causing the issue, but the theme campaign. `framework-customizations` is not Redux Framework.

Also we did not develop that theme. You'll need to contact the actual author. Good luck!
