### ISSUE TITLE
Issue with multiple required arguments

### ISSUE THREAD

**Issue by Mobilyzz** [reduxframework/redux-framework#2919] opened 2016-04-11 10:04 UTC
Hello,

First of all, thanks for providing us an excellent framework. :)

Coming back to the topic: we have a condition, let's say we have Option 1, Option 2 and Option 3

Now, option 2 has 
`required => array('option1','=','val1');`

and option3 has
```
required => array(
    array('option1','=','val2'), 
    array('option2','=',false)
);
```

Now, what happens is selecting `val2` in option1 hides option2 which in turn hides option3 as well because option2 is no more visible.

**Comment by kprovance** [comment] 2016-04-14 03:11
PLease review:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by kprovance** [comment] 2016-04-16 16:58
Closing due to lack of reply.

**Closed by kprovance** 2016-04-16 16:58 UTC

**Comment by Mobilyzz** [comment] 2016-04-17 01:21
We are not looking for support, we understand the rules and just want to report abnormal behaviour. If you need more info, just let us know.

**Comment by dovy** [comment] 2016-04-17 01:24
@Mobilyzz That's expected behavior. You're nesting required. The "top" required will always trickle down to it's children.  ;)
