### ISSUE TITLE
Customizer live preview does not load changes of color gradient.

### ISSUE THREAD

**Issue by stergjyshi** [reduxframework/redux-framework#3949] opened 2023-05-02 11:59 UTC
I noticed this error while using color gradient option on settings panel
Uncaught TypeError: el.find(...).propr is not a function on line 53
`el.find( '#' + e.target.getAttribute( 'data-id' ) + '-transparency' ).propr( 'checked', false );`

Replaced the above line 53 on redux-color-gradient.js with `el.find( '#' + e.target.getAttribute( 'data-id' ) + '-transparency' ).prop( 'checked', false );` 

with this change there are no console errors any more but there is no live preview of the results on customizer using gradients, problem was same before my changes other color options are fine, issue with color gradient only.

**Comment by kprovance** [comment] 2023-05-02 16:23
Hi,

The error of which you speak is fixed in the beta version, in this repo. Also, I am unable to recreate the customizer issue. The gradient field works as intended.  But, none of the requested and required info we asked for when this ticket was opened was included, so I am unable to speculate further.

Good luck.

**Closed by kprovance** 2023-05-02 16:23 UTC
