### ISSUE TITLE
Integrating Redux framework to theme causing to custom and plugin shortcodes

### ISSUE THREAD

**Issue by maksolutionz** [reduxframework/redux-framework#2696] opened 2015-11-02 06:39 UTC
Integrating Redux framework to theme causing to custom and plugin shortcodes to stop working, also woocommerce showing message 
"Your theme does not declare WooCommerce support – Please read our integration guide or check out our Storefront theme which is totally free to download and designed specifically for use with WooCommerce.", 

While do_shortcode working in my template files, but using them from editor, shortcodes stop workking

**Comment by kprovance** [comment] 2015-11-02 06:57
The WOo thing you need to take up with Woo.  Not our plugin.

Everything else, please review our support guidelines and post back the required information.

**Comment by maksolutionz** [comment] 2015-11-02 07:05
Its not about only woo, all plugins short codes stop working, even my
custom created short code not working from editor, i switchthe theme with
out redux, my shortcodes working fine for me. do some thing for this,
otherwise it will be called bug in your plugin, because only redux can not
provide all the functionality in a large scale website, like membership
functionality etc....

**Comment by maksolutionz** [comment] 2015-11-02 07:09
For your information, i have also wrote that, all plugins short code stop working by redux, not anly woo, i have issue with short code functionality disturbance.

**Comment by kprovance** [comment] 2015-11-02 07:12
Well, whatever.  You've included no information requested in our support guidelines.  If you're not going to supply it, then please close the ticket.  My theme uses Redux and Woo together, and I experience no shortcode issues.  The problem is mostly likely in your config, or code.  Again, since all you basically said was 'it don't work,' I can do nothing more.

**Comment by kprovance** [comment] 2015-11-05 06:01
Closing issue due to lack of reply.  If you continue to experience issues, please open a new ticket with the required information.  Thanks!

**Closed by kprovance** 2015-11-05 06:01 UTC
