### ISSUE TITLE
framework.php:884 PHP Warning after going from 3.5.4.3 to 3.5.5.1

### ISSUE THREAD

**Issue by benvoynick** [reduxframework/redux-framework#2462] opened 2015-07-09 21:44 UTC
I tried installing 3.5.5.1 on a test site for my theme, and with that version, a warning triggers on page templates where I call the get_default_value method on a media field, if that media field is empty. (That is, the Remove button was used to blank the field, and it was then saved without selecting a different media file.)

Below, the call that initiates the problem. ($reduxConfig->ReduxFrameWork is a ReduxFramework object.)

```
$reduxConfig->ReduxFramework->get_default_value('header-site-navigation-logo-image');
```

Here is the array of settings for that field. (Part of a legacy setup, $this->sections[] = array etc...)

```
array(
	'id'      => 'header-site-navigation-logo-image',
	'type'    => 'media',
	'title'   => 'Site logo for navigation menu',
	'desc'    => '<p>Some text</p><p><strong>Text<br>Text</strong><br>Text</p>',
	'preview' => true,
	'default' => array(
		'url' => 'http://url.com/path/img.png',
		'width' => 100,
		'height' => 68,
	),
),
```

and the warning:

```
[error] PHP Warning:  Invalid argument supplied for foreach() in /***website-path***/wordpress/wp-content/plugins/redux-framework/ReduxCore/framework.php on line 884, referer: http://***website***/wp-admin/admin.php?page=mytheme_options&tab=0
[error] PHP Stack trace:, referer: http://***website***/wp-admin/admin.php?page=mytheme_options&tab=0
[error] PHP   1. {main}() /***website-path***/wordpress/index.php:0, referer: http://***website***/wp-admin/admin.php?page=mytheme_options&tab=0
[error] PHP   2. require() /***website-path***/wordpress/index.php:17, referer: http://***website***/wp-admin/admin.php?page=mytheme_options&tab=0
[error] PHP   3. require_once() /***website-path***/wordpress/wp-blog-header.php:16, referer: http://***website***/wp-admin/admin.php?page=mytheme_options&tab=0
[error] PHP   4. include() /***website-path***/wordpress/wp-includes/template-loader.php:74, referer: http://***website***/wp-admin/admin.php?page=mytheme_options&tab=0
[error] PHP   5. get_header() /opt/ucp/wordpress/themes/mytheme/dev/index.php:15, referer: http://***website***/wp-admin/admin.php?page=mytheme_options&tab=0
[error] PHP   6. locate_template() /***website-path***/wordpress/wp-includes/general-template.php:45, referer: http://***website***/wp-admin/admin.php?page=mytheme_options&tab=0
[error] PHP   7. load_template() /***website-path***/wordpress/wp-includes/template.php:477, referer: http://***website***/wp-admin/admin.php?page=mytheme_options&tab=0
[error] PHP   8. require_once() /***website-path***/wordpress/wp-includes/template.php:501, referer: http://***website***/wp-admin/admin.php?page=mytheme_options&tab=0
[error] PHP   9. ReduxFramework->get_default_value() /opt/ucp/wordpress/themes/mytheme/dev/header.php:326, referer: http://***website***/wp-admin/admin.php?page=mytheme_options&tab=0
[error] PHP  10. ReduxFramework->_default_values() /***website-path***/wordpress/wp-content/plugins/redux-framework/ReduxCore/framework.php:1115, referer: http://***website***/wp-admin/admin.php?page=mytheme_options&tab=0
[error] PHP  11. ReduxFramework->field_default_values() /***website-path***/wordpress/wp-content/plugins/redux-framework/ReduxCore/framework.php:1224, referer: http://***website***/wp-admin/admin.php?page=mytheme_options&tab=0
[error] PHP  12. ReduxFramework->get_wordpress_data() /***website-path***/wordpress/wp-content/plugins/redux-framework/ReduxCore/framework.php:1158, referer: http://***website***/wp-admin/admin.php?page=mytheme_options&tab=0
```

I reverted to 3.5.4.3 and the warning went away.

When using 3.5.5.1, I also get a similar warning when in the WordPress dashboard:

```
[error] PHP Warning:  Invalid argument supplied for foreach() in /***website-path***/wordpress/wp-content/plugins/redux-framework/ReduxCore/framework.php on line 884, referer: http://***website***
[error] PHP Stack trace:, referer: http://***website***
[error] PHP   1. {main}() /***website-path***/wordpress/wp-admin/index.php:0, referer: http://***website***
[error] PHP   2. require_once() /***website-path***/wordpress/wp-admin/index.php:10, referer: http://***website***
[error] PHP   3. do_action() /***website-path***/wordpress/wp-admin/admin.php:158, referer: http://***website***
[error] PHP   4. call_user_func_array() /***website-path***/wordpress/wp-includes/plugin.php:496, referer: http://***website***
[error] PHP   5. ReduxFramework->_register_settings() /***website-path***/wordpress/wp-includes/plugin.php:496, referer: http://***website***
[error] PHP   6. ReduxFramework->_default_values() /***website-path***/wordpress/wp-content/plugins/redux-framework/ReduxCore/framework.php:2007, referer: http://***website***
[error] PHP   7. ReduxFramework->field_default_values() /***website-path***/wordpress/wp-content/plugins/redux-framework/ReduxCore/framework.php:1224, referer: http://***website***
[error] PHP   8. ReduxFramework->get_wordpress_data() /***website-path***/wordpress/wp-content/plugins/redux-framework/ReduxCore/framework.php:1158, referer: http://***website***
```

This is on Ubuntu 12.04, the PHP version reports as 5.3.10-1ubuntu3.17. I can supply more theme code if it would be helpful.

**Comment by kprovance** [comment] 2015-07-09 21:58
According to that trace info, the problem is not in the config code you supplied, it's in another array, one that uses the `data` argument.  The `get_default_value` function cycles through all the default values of your config (it has to, obviously).  At some point it's hitting an array that polls for wordpress data via the `data` argument.  I'd start by looking in your config for any field array that uses that arg and ensure it's correct.  if it looks correct, comment it out (if multiple, then comment them all out) and see if the problem goes away, if so, add them back one at a time until you find the offender.  Once you do, post it back.

**Comment by kprovance** [comment] 2015-07-13 18:41
Closing due to lack of reply.

**Closed by kprovance** 2015-07-13 18:41 UTC

**Comment by benvoynick** [comment] 2015-07-15 19:21
Thank you! I was able to find the issue following your advice.

The problem was a blank args argument:

```
array(
	'id'       => 'users-login-role-to-redirect',
	'type'     => 'select',
	'multi'    => true,
	'data'     => 'roles',
	'args'     => '',
	'required' => array('users-login-redirect-a-role', 'equals', true),
	'permissions' => 'edit_users',
	'title'    => 'Roles to redirect',
	'desc'     => '<p>Users with a Role selected in this box will be subject to this redirect on log in.</p><p>Users with other Roles will not.</p>',
	'placeholder' => 'No Roles selected.'
),
```

Removing the `'args' => '',` line gets rid of the warning.

**Comment by kprovance** [comment] 2015-07-15 19:25
`args` requires an array.  Says so here: https://docs.reduxframework.com/core/fields/select/
