### ISSUE TITLE
reduxframework conflict with yoast seo plugin

### ISSUE THREAD

**Issue by tiantzer** [reduxframework/redux-framework#3536] opened 2018-06-13 03:38 UTC
Hi,

I've found the reduxframework plugin had conflict problem with yoast seo plugin, which is the loading extra page of the categories. 

example: when I get into my woocommerce shop page 1 and the conflict will loading the shop page 2 on the background and you have to use the firefox inspector tool to see it.

thanks for provide this such wonderful plugin.

**Comment by kprovance** [comment] 2018-06-13 03:41
We need you to provide the information specifically asked for, and is required.  Please provide evidence on how redux is the cause, besides "it's loaded".

**Comment by tiantzer** [comment] 2018-06-13 04:00
Hi, 

Please exam this screenshot : [https://imgur.com/a/KqvctZW](https://imgur.com/a/KqvctZW)
I'm browsing the page one of clect category, But when I activate the yoast seo plugin in the meantime the page two of clect category will been loaded. The **2004 ms** loading time and **/product-category/clect/2** shouldn't happen.

thanks.

**Comment by kprovance** [comment] 2018-06-13 04:29
Okay, first, you have not provided any of the information we asked for.   This is required.  Please click New Issue and read all the test you deleted out.  That is what we require.  

Second, I really do not see how Redux is related to this.  I assume you are the theme author?  I need you to show me how Redux is related to this.

**Comment by kprovance** [comment] 2018-06-15 06:48
No reply.  Closing.

**Closed by kprovance** 2018-06-15 06:48 UTC
