### ISSUE TITLE
field_spinner.php Small issue need to be fixed

### ISSUE THREAD

**Issue by OuiT** [reduxframework/redux-framework#3201] opened 2017-01-02 03:46 UTC
Hello,
Just want to help to fix this issue
 error Notice found :
> Notice: Undefined index: output in  redux-framework\ReduxCore\inc\fields\spinner\field_spinner.php on line 156:

Wrong Code : 
`$css = $this->parseCSS($this->value, $this->field['output']);`

Right Code : 

`$css = $this->parseCSS($this->value, $this->field['compiler']);`

 Best Regards,

**Comment by kprovance** [comment] 2017-01-02 03:47
Support URL?  Versions?  Code to reproduce?  All the text we included in the new issue window needed to be read and followed.

**Comment by OuiT** [comment] 2017-01-02 03:47
Also If possible to add output feature to field_slider.php this will be awesome

**Comment by OuiT** [comment] 2017-01-02 03:50
oh Im not asking for help , Just noticed you to know the issue to fix it on next versions.
Redux version : v3.6.3
Wordpress Version 4.7

**Comment by kprovance** [comment] 2017-01-02 06:00
Fixed in 3.6.3.3.  Next time, please include the requested info.  Just because you think we don't need it doesn't really mean we don't.  it's more work for me to verify this without it.

**Closed by kprovance** 2017-01-02 06:00 UTC
