### ISSUE TITLE
Redux Framework Causing Double Page Load

### ISSUE THREAD

**Issue by MarBelle** [reduxframework/redux-framework#3614] opened 2018-12-12 12:47 UTC
Hi,

I updated to the latest version of Redux Framework (3.6.15) today and immediately noticed that my site was hit with a strange “double load” issue – i.e. the post loads initially for a second, then goes to a white screen for 2-4secs, then loads again and settles.

I’ve gone through the process of disabling all plugins and then only activating Redux Framework which causes the problem to reoccur.

As this error was new to me and I couldn’t remember which version of Redux Framework was installed prior to the update (as I hadn’t updated for a while) I worked backwards installing previous versions of the plugin until Redux Framework 3.69 which doesn’t cause the double load issue.

You can see the 3.6.15 error on my test blog: https://new.directorsnotes.com/
And the 3.6.9 version working correctly at: https://directorsnotes.com

As this plugin is integral to the correct functioning of my theme to behave correctly would be massively appreciated.

Thanks
MarBelle

**Comment by kprovance** [comment] 2018-12-12 14:48
I'm not seeing the requested and required information as asked for in the new issue window.  It's needed for free support.

I looked at both pages.  I see no reloading or white screens or flashes of any kind.  Do you have any other reason to suspect redux besides turning it off?   You could try disabling async typography, see if that's causing a flash.  Otherwise. I can't see or don't see what you are describing.

**Comment by MarBelle** [comment] 2018-12-12 15:02
Sorry I think that's because I provided links to the home page:
All the post pages (on new.directorsnotes.com) exhibit the 'white screen' behaviour for example https://new.directorsnotes.com/2014/01/13/theyareanimators18/

whilst the equivalent page of https://directorsnotes.com/2014/01/13/theyareanimators18/ running Redux Framework 3.6.9 loads as expected

**Comment by kprovance** [comment] 2018-12-12 15:15
Okay.  Again, the request information is not provided.  I at least need that support hash described in the new issue window.

I don't think this is Redux.  If you look at your console log while loading the two pages, there is one distinct different.  The https://new.directorsnotes.com/2014/01/13/theyareanimators18/ page displays this message during what appears to be a 'reload/flash' (which it isn't, whatever is making this call to twitter is slowing it down.  

![image](https://user-images.githubusercontent.com/3412363/49878900-b6798700-fdf6-11e8-976e-c88c9c4ae096.png)

This does not occur on the other page, the one that loads smoother.  Try disabling whatever is causing that message and see if it fixes it.

**Comment by kprovance** [comment] 2018-12-19 23:49
I am going to assume the twitter module errors was the cause of this, not having heard back about it.  Closing.

**Closed by kprovance** 2018-12-19 23:49 UTC
