### ISSUE TITLE
 framework warning.(unble to access custom css)

### ISSUE THREAD

**Issue by harmancheema93** [reduxframework/redux-framework#3171] opened 2016-11-22 09:10 UTC
following error appears in wp theme setting :
Redux Framework Warning
select2-css CDN unavailable. Some controls may not render properly. Please wait a few minutes, then try refreshing the page. Unable to load some remotely hosted scripts.

Redux Framework Warning
select2-js CDN unavailable. Some controls may not render properly. Please wait a few minutes, then try refreshing the page. Unable to load some remotely hosted scripts.

Redux Framework Warning
ace-editor-js CDN unavailable. Some controls may not render properly. Please wait a few minutes, then try refreshing the page. Unable to load some remotely hosted scripts.

**Comment by kprovance** [comment] 2016-11-22 14:40
Please refer to the pre-printed text from the 'new issue' window.  None of the info we asked for was given:

Hello, and welcome to Redux Framework!

Are you a user reporting a bug with a theme or plugin?
======================================================
Redux is a tool for developers to include an options panel in their project. Consequently, we do not offer support for folks who have purchased a theme or plugin that uses Redux. The responsibility of support for themes and plugins falls upon it's author. We realize that some authors have included support links for Redux in their projects, when they should not have. We do apologize for that confusion and are taking steps to remedy this confusion. 

If you have purchased a theme or plugin that utilizes Redux, please contact the author for support. If the author is unavailable for support or has discontinued support, please refer to this before posting to our issue tracker: https://docs.reduxframework.com/core/support-defined/
	
Have a development usage question?
==================================
The issue tracker isn't the best place for usage questions. This format is not well-suited for Q&A, and questions here don't have as much visibility as they do elsewhere. Before you ask a question, here are some resources to get help first:

- Try Redux: https://demo.reduxframework.com/
- Read the docs: https://docs.reduxframework.com/
- Look for/ask questions on StackOverflow: https://stackoverflow.com/questions/tagged/redux-framework
- Ask in our community Slack channel: http://slack.redux.io/
- For Premium support or advanced customizations we offer premium support. See https://reduxframework.com/extension/premium-support/ for more information.

Questions about a Redux extension?
==================================
All pre-sale and support for premium extensions need to be posted to the Redux Extensions Issue Tracker. Please do not post them to this issue tracker. https://github.com/reduxframework/redux-extensions/

Think you found a bug?
======================
Please use the "BUG REPORT" template below. Remember, we are rabbid about backwards compatability. Do not submit fixes that break previous ways of doing so or they will be rejected.

Also, unless you provide a Support Hash, your request will also be rejected. See https://docs.reduxframework.com/core/generating-a-support-hash/ for more details.

You MUST be using Redux in dev mode when submitting an issue to us. If you are not, or have circumvented our dev mode protocol, you are on your own. There could be information in your issue that requires dev move active. (Compressed Javascript, for example. We are unable to diagnose issues with compressed Javascript and why dev mode needs to be enabled.)

If an error or notice appears on your screen, please cut and paste it into your issue. PLEASE, do not say you 'got an error' without telling us what the error or notice is.

Before you post, check the JavaScript!
======================================
Sometimes, an issue may be tied to JavaScript. To make this determination, you will need to check the JavaScript console. To do this, ensure your web browser is the topmost window. On your keyboard, press CTRL+SHIFT+I. The JavaScript console will open. If there are notices or errors there, please cut and paste them into your issue. We would prefer a cut and paste, since it will include all pertinent information. Also, Redux dev mode must be enabled so an accurate line number may be reported.


## Support Hash

## Steps to reproduce

## Expected Behavior

## Actual Behavior

## Any Error Details (PHP/JavaScript)

**Comment by kprovance** [comment] 2016-11-25 14:17
No reply with requested information.  Closing.

**Closed by kprovance** 2016-11-25 14:17 UTC

**Comment by DavidRe9** [comment] 2018-11-18 02:50
Can add this line on wp-config:

/**
*  The constant WP_ACCESSIBLE_HOSTS will allow additional hosts to go through for requests
*/
define('WP_ACCESSIBLE_HOSTS', 'cdn.jsdelivr.net,look.redux.io,');

**Comment by dovy** [comment] 2018-11-18 16:32
Good call. @kprovance can we add this?

**Comment by kprovance** [comment] 2018-11-18 21:05
I guess I can look into it?  If this is one of those things that has to be set in the wp-config explicitly, then probably not.  If WP is more flexible, then we could make ti a global arg.  I'll see what the codex )and the internet) says.

**Comment by kprovance** [comment] 2018-11-18 22:14
As suspect, that define needs to be set in the wp-config.  It's not something that will do much good to set after the WP core has loaded.  And I don;t see a WP hook to circumvent that.

It really should not make a difference, however.  These are the two constants that work in tandem:
```php
define( 'WP_HTTP_BLOCK_EXTERNAL', true );
define( 'WP_ACCESSIBLE_HOSTS', 'api.wordpress.org,*.github.com' ); // Only allow particular hosts in
```

These were fixes for the old timthumb issue:  https://www.wpbeginner.com/wp-tutorials/how-to-fix-and-cleanup-the-timthumb-hack-in-wordpress/

WP_ACCESSIBLE_HOSTS would limit the scope of particular hosts, whitelisting, basically.  Adding this to the wp-config - if I am reading this correctly - won;t make that much of a difference and may in fact block out other hosts that need to come through, as all of them are allowed by default.

The most common reason for the CDN error is either the CDN being down, or working from a localhost with no on firewalled internet access.

**Comment by kprovance** [comment] 2018-11-18 22:29
All that really does it make it easy for people who don't know how to edit the wp-config directly.  It's still editing the config file itself.  It doesn't change the actual intention of the define or it's purpose.  If it works for you, that's great.   It's not something we can add to Redux itself, as the define needs to be set in the wp-config.
